/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DeployGuard 분석 엔진
 * 
DeployGuard는 Kubernetes 및 AWS 인프라의 공격 경로를 분석하고 최적의 보안 조치를 권장합니다.

## Scanner Lifecycle

1. **클러스터 등록**: `POST /api/v1/clusters` → API 토큰 발급
2. **Scanner 설치**: 발급된 토큰으로 Helm 차트 배포
3. **Polling**: `GET /api/v1/scans/pending` (Bearer 인증)
4. **업로드**: `POST /api/v1/scans/{scan_id}/upload-url`
5. **완료**: `POST /api/v1/scans/{scan_id}/complete` → Analysis 파이프라인 트리거

 * OpenAPI spec version: 4.0.0
 */

export interface AnalysisJobResponse {
  /** 생성된 분석 작업 ID */
  job_id: string;
  /** 작업 상태 */
  status: string;
  /** 상태 메시지 */
  message: string;
}
