/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DeployGuard 분석 엔진
 * 
DeployGuard는 인프라 그래프를 구축하고, 공격 경로를 탐색하며, 최적의 조치를 권장함으로써 Kubernetes 및 AWS 인프라 보안을 분석합니다.

## Scanner Orchestration Lifecycle

1. **Cluster registration**: `POST /api/v1/clusters`
2. **API token issuance**: scanner API token is managed in the cluster onboarding flow (not exposed by a dedicated public endpoint in this service)
3. **Scanner Helm installation**: scanner is installed with the issued token
4. **Scanner polling**: `GET /api/v1/scans/pending` with `Authorization: Bearer <api_token>`
5. **Scan execution + upload**: scanner uploads files via `POST /api/v1/scans/{scan_id}/upload-url`
6. **Completion notification**: scanner calls `POST /api/v1/scans/{scan_id}/complete`
7. **Analysis pipeline stage**: service transitions scan to `processing` and triggers only the implemented orchestration check (`maybe_trigger_analysis`)

 * OpenAPI spec version: 4.0.0
 */
import type { ScannerType } from './scannerType';

export type ClaimPendingScanApiV1ScansPendingGetParams = {
scanner_type: ScannerType;
claimed_by?: string | null;
/**
 * @minimum 1
 */
lease_seconds?: number;
};
