/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DeployGuard 분석 엔진
 * 
DeployGuard는 Kubernetes 및 AWS 인프라의 공격 경로를 분석하고 최적의 보안 조치를 권장합니다.

## Scanner Lifecycle

1. **클러스터 등록**: `POST /api/v1/clusters` → API 토큰 발급
2. **Scanner 설치**: 발급된 토큰으로 Helm 차트 배포
3. **작업 생성**: 대시보드 또는 스케줄러가 `POST /api/v1/scans/start` 호출 → `created` 작업 생성
4. **작업 클레임**: 워커가 `GET /api/v1/scans/pending` 폴링 (Bearer 인증) → created 작업 claim
5. **실행 및 업로드**: claim한 워커가 실제 스캔 실행 후 `POST /api/v1/scans/{scan_id}/upload-url` 사용
6. **완료 보고**: 워커가 `POST /api/v1/scans/{scan_id}/complete` 호출 → Analysis 파이프라인 트리거

 * OpenAPI spec version: 4.0.0
 */

export interface ClusterCreateRequest {
  /**
   * 클러스터 고유 이름
   * @minLength 1
   * @maxLength 255
   */
  name: string;
  /** 클러스터 설명 */
  description?: string | null;
  /** 클러스터 유형: 'eks' | 'self-managed' | 'aws' */
  cluster_type?: string | null;
  /** Discovery Inventory용 AWS account id */
  aws_account_id?: string | null;
  /** Discovery sync용 AssumeRole ARN */
  aws_role_arn?: string | null;
  /** Discovery Inventory 기본 AWS 리전 */
  aws_region?: string | null;
}
