/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DeployGuard 분석 엔진
 * 
DeployGuard는 인프라 그래프를 구축하고, 공격 경로를 탐색하며, 최적의 조치를 권장함으로써 Kubernetes 및 AWS 인프라 보안을 분석합니다.

## 스캔 데이터 수집 흐름

1. **스캔 세션 시작**: `POST /api/scans/start` → `scan_id` 수신
2. **업로드 URL 요청**: `POST /api/scans/{scan_id}/upload-url` → S3 presigned URL 수신
3. **파일 업로드**: presigned URL로 파일을 직접 `PUT` (클라이언트 → S3)
4. **스캔 완료 알림**: `POST /api/scans/{scan_id}/complete` → 분석 파이프라인 트리거

 * OpenAPI spec version: 4.0.0
 */

export interface ClusterResponse {
  /** 클러스터 고유 ID */
  id: string;
  /** 클러스터 이름 */
  name: string;
  /** 클러스터 설명 */
  description?: string | null;
  /** 클러스터 유형 */
  cluster_type: string;
  /** 생성 일시 */
  created_at: string;
  /** 최종 수정 일시 */
  updated_at: string;
}
