/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DeployGuard 분석 엔진
 * 
DeployGuard는 Kubernetes 및 AWS 인프라의 공격 경로를 분석하고 최적의 보안 조치를 권장합니다.

## Scanner Lifecycle

1. **클러스터 등록**: `POST /api/v1/clusters` → API 토큰 발급
2. **Scanner 설치**: 발급된 토큰으로 Helm 차트 배포
3. **작업 생성**: 대시보드 또는 스케줄러가 `POST /api/v1/scans/start` 호출 → `queued` 작업 생성
4. **작업 클레임**: 워커가 `GET /api/v1/scans/pending` 폴링 (Bearer 인증) → queued 작업 claim
5. **실행 및 업로드**: claim한 워커가 실제 스캔 실행 후 `POST /api/v1/scans/{scan_id}/upload-url` 사용
6. **완료 보고**: 워커가 `POST /api/v1/scans/{scan_id}/complete` 호출 → Analysis 파이프라인 트리거

 * OpenAPI spec version: 4.0.0
 */
import type { ClusterOnboardingResponse } from './clusterOnboardingResponse';

export interface ClusterCreateResponse {
  /** 클러스터 고유 ID */
  id: string;
  /** 클러스터 이름 */
  name: string;
  /** 클러스터 설명 */
  description?: string | null;
  /** 클러스터 유형 */
  cluster_type: string;
  /** 스캐너 인증용 API 토큰 */
  api_token: string;
  /** 클러스터 유형별 설치 가이드 */
  onboarding: ClusterOnboardingResponse;
  /** 생성 일시 */
  created_at: string;
  /** 최종 수정 일시 */
  updated_at: string;
}
