/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DeployGuard 분석 엔진
 * 
DeployGuard는 Kubernetes 및 AWS 인프라의 공격 경로를 분석하고 최적의 보안 조치를 권장합니다.

## Scanner Lifecycle

1. **클러스터 등록**: `POST /api/v1/clusters` → API 토큰 발급
2. **Scanner 설치**: 발급된 토큰으로 Helm 차트 배포
3. **작업 생성**: 대시보드 또는 스케줄러가 `POST /api/v1/scans/start` 호출 → `created` 작업 생성
4. **작업 클레임**: 워커가 `GET /api/v1/scans/pending` 폴링 (Bearer 인증) → created 작업 claim
5. **실행 및 업로드**: claim한 워커가 실제 스캔 실행 후 `POST /api/v1/scans/{scan_id}/upload-url` 사용
6. **완료 보고**: 워커가 `POST /api/v1/scans/{scan_id}/complete` 호출 → 스캔 완료만 기록
7. **분석 작업 생성**: 사용자가 `POST /api/v1/analysis/jobs` 호출 → 선택한 scan_id로 analysis_jobs 생성
8. **분석 실행**: 사용자가 `POST /api/v1/analysis/jobs/{job_id}/execute` 호출

 * OpenAPI spec version: 4.0.0
 */

export type ExplanationProviderName = typeof ExplanationProviderName[keyof typeof ExplanationProviderName];


export const ExplanationProviderName = {
  openai: 'openai',
  xai: 'xai',
} as const;
