/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DeployGuard 분석 엔진
 * 
DeployGuard는 Kubernetes 및 AWS 인프라의 공격 경로를 분석하고 최적의 보안 조치를 권장합니다.

## Scanner Lifecycle

1. **클러스터 등록**: `POST /api/v1/clusters` → API 토큰 발급
2. **Scanner 설치**: 발급된 토큰으로 Helm 차트 배포
3. **작업 생성**: 대시보드 또는 스케줄러가 `POST /api/v1/scans/start` 호출 → `created` 작업 생성
4. **작업 클레임**: 워커가 `GET /api/v1/scans/pending` 폴링 (Bearer 인증) → created 작업 claim
5. **실행 및 업로드**: claim한 워커가 실제 스캔 실행 후 `POST /api/v1/scans/{scan_id}/upload-url` 사용
6. **완료 보고**: 워커가 `POST /api/v1/scans/{scan_id}/complete` 호출 → 스캔 완료만 기록
7. **분석 작업 생성**: 사용자가 `POST /api/v1/analysis/jobs` 호출 → 선택한 scan_id로 analysis_jobs 생성
8. **분석 실행**: 사용자가 `POST /api/v1/analysis/jobs/{job_id}/execute` 호출

 * OpenAPI spec version: 4.0.0
 */
import type { InvAssetItemMetadata } from './invAssetItemMetadata';
import type { InvAssetItemScannerCoverage } from './invAssetItemScannerCoverage';
import type { InvAssetItemTimestamps } from './invAssetItemTimestamps';

/**
 * 자산 목록 단일 아이템
 */
export interface InvAssetItem {
  /** 자산 식별자. 예: ec2:i-0abc123 / pod:prod/web-abc */
  node_id: string;
  /** ec2 | s3 | rds | iam_role | iam_user | pod | service | ... */
  node_type: string;
  /** k8s | aws */
  domain: string;
  name: string;
  /** K8s 자산만 해당. AWS는 null. */
  namespace?: string | null;
  /** AWS 자산만 해당. K8s는 null. */
  account_id?: string | null;
  /** AWS 자산 중 region 있는 것만 해당. */
  region?: string | null;
  /** [임시값] graph 미연동. 항상 false (MVP). */
  is_entry_point?: boolean;
  /** [임시값] graph 미연동. 항상 false (MVP). */
  is_crown_jewel?: boolean;
  /** [임시값] graph 미연동. null (MVP). */
  base_risk?: number | null;
  /** scanner_type → covered | not_covered. node_type 기반 매핑 + scan_records 근사. */
  scanner_coverage?: InvAssetItemScannerCoverage;
  /** 원본 API에서 가져온 자산 상세 속성 (raw_result_json 기반). */
  metadata?: InvAssetItemMetadata;
  /** last_scan_at: scan_records 기준 / last_analysis_at: graph 기준 (MVP: null). */
  timestamps?: InvAssetItemTimestamps;
}
