/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * DeployGuard 분석 엔진
 * 
DeployGuard는 Kubernetes 및 AWS 인프라의 공격 경로를 분석하고 최적의 보안 조치를 권장합니다.

## Scanner Lifecycle

1. **클러스터 등록**: `POST /api/v1/clusters` → API 토큰 발급
2. **Scanner 설치**: 발급된 토큰으로 Helm 차트 배포
3. **작업 생성**: 대시보드 또는 스케줄러가 `POST /api/v1/scans/start` 호출 → `created` 작업 생성
4. **작업 클레임**: 워커가 `GET /api/v1/scans/pending` 폴링 (Bearer 인증) → created 작업 claim
5. **실행 및 업로드**: claim한 워커가 실제 스캔 실행 후 `POST /api/v1/scans/{scan_id}/upload-url` 사용
6. **완료 보고**: 워커가 `POST /api/v1/scans/{scan_id}/complete` 호출 → 스캔 완료만 기록
7. **분석 작업 생성**: 사용자가 `POST /api/v1/analysis/jobs` 호출 → 선택한 scan_id로 analysis_jobs 생성
8. **분석 실행**: 사용자가 `POST /api/v1/analysis/jobs/{job_id}/execute` 호출

 * OpenAPI spec version: 4.0.0
 */
import type { InvRiskSummary } from './invRiskSummary';
import type { InvSummaryResponseAwsResources } from './invSummaryResponseAwsResources';
import type { InvSummaryResponseK8sResources } from './invSummaryResponseK8sResources';
import type { InvSummaryResponseScannerCoverage } from './invSummaryResponseScannerCoverage';

/**
 * GET /inventory/summary 응답
 */
export interface InvSummaryResponse {
  cluster_id: string;
  cluster_name: string;
  /** 최신 graph_snapshot 기준 분석 완료 시각. MVP: graph 미연동으로 null. */
  last_analysis_at?: string | null;
  /** 전체 자산 수 (snapshot 기반) */
  total_node_count: number;
  /** K8s 자산 타입별 카운트. MVP: snapshot 없으면 빈 dict. */
  k8s_resources?: InvSummaryResponseK8sResources;
  /** AWS 자산 타입별 카운트. snapshot raw_result_json 기반. */
  aws_resources?: InvSummaryResponseAwsResources;
  /** scanner_type → 커버리지 상세. scan_records 기반 근사값 (MVP). */
  scanner_coverage?: InvSummaryResponseScannerCoverage;
  /** 위험 요약. MVP: graph 미연동으로 전부 0 (임시값). */
  risk_summary?: InvRiskSummary;
}
