name: Deploy Dashboard

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: self-hosted

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set image tag
        id: vars
        run: echo "TAG=${GITHUB_SHA}" >> $GITHUB_OUTPUT


      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2


      - name: Build Docker image
        run: |
          docker build \
          -t ${{ secrets.ECR_REPOSITORY }}:${{ steps.vars.outputs.TAG }} \
          .


      - name: Tag Docker image
        run: |
          docker tag \
          ${{ secrets.ECR_REPOSITORY }}:${{ steps.vars.outputs.TAG }} \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ steps.vars.outputs.TAG }}

          docker tag \
          ${{ secrets.ECR_REPOSITORY }}:${{ steps.vars.outputs.TAG }} \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest


      - name: Push Docker image
        run: |
          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:${{ steps.vars.outputs.TAG }}

          docker push \
          ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest


      - name: Restart container
        run: |
          IMAGE=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}:latest

          docker pull $IMAGE

          docker rm -f deployguard-dashboard || true

          docker run -d \
            -p 3000:80 \
            --name deployguard-dashboard \
            $IMAGE